// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __encrypt_128_key_ebkb_H__
#define __encrypt_128_key_ebkb_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct encrypt_128_key_ebkb_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 8;
  static const unsigned AddressRange = 1024;
  static const unsigned AddressWidth = 10;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in <sc_lv<AddressWidth> > address1;
sc_core::sc_in <sc_logic> ce1;
sc_core::sc_out <sc_lv<DataWidth> > q1;
sc_core::sc_in <sc_lv<AddressWidth> > address2;
sc_core::sc_in <sc_logic> ce2;
sc_core::sc_out <sc_lv<DataWidth> > q2;
sc_core::sc_in <sc_lv<AddressWidth> > address3;
sc_core::sc_in <sc_logic> ce3;
sc_core::sc_out <sc_lv<DataWidth> > q3;
sc_core::sc_in <sc_lv<AddressWidth> > address4;
sc_core::sc_in <sc_logic> ce4;
sc_core::sc_out <sc_lv<DataWidth> > q4;
sc_core::sc_in <sc_lv<AddressWidth> > address5;
sc_core::sc_in <sc_logic> ce5;
sc_core::sc_out <sc_lv<DataWidth> > q5;
sc_core::sc_in <sc_lv<AddressWidth> > address6;
sc_core::sc_in <sc_logic> ce6;
sc_core::sc_out <sc_lv<DataWidth> > q6;
sc_core::sc_in <sc_lv<AddressWidth> > address7;
sc_core::sc_in <sc_logic> ce7;
sc_core::sc_out <sc_lv<DataWidth> > q7;
sc_core::sc_in <sc_lv<AddressWidth> > address8;
sc_core::sc_in <sc_logic> ce8;
sc_core::sc_out <sc_lv<DataWidth> > q8;
sc_core::sc_in <sc_lv<AddressWidth> > address9;
sc_core::sc_in <sc_logic> ce9;
sc_core::sc_out <sc_lv<DataWidth> > q9;
sc_core::sc_in <sc_lv<AddressWidth> > address10;
sc_core::sc_in <sc_logic> ce10;
sc_core::sc_out <sc_lv<DataWidth> > q10;
sc_core::sc_in <sc_lv<AddressWidth> > address11;
sc_core::sc_in <sc_logic> ce11;
sc_core::sc_out <sc_lv<DataWidth> > q11;
sc_core::sc_in <sc_lv<AddressWidth> > address12;
sc_core::sc_in <sc_logic> ce12;
sc_core::sc_out <sc_lv<DataWidth> > q12;
sc_core::sc_in <sc_lv<AddressWidth> > address13;
sc_core::sc_in <sc_logic> ce13;
sc_core::sc_out <sc_lv<DataWidth> > q13;
sc_core::sc_in <sc_lv<AddressWidth> > address14;
sc_core::sc_in <sc_logic> ce14;
sc_core::sc_out <sc_lv<DataWidth> > q14;
sc_core::sc_in <sc_lv<AddressWidth> > address15;
sc_core::sc_in <sc_logic> ce15;
sc_core::sc_out <sc_lv<DataWidth> > q15;
sc_core::sc_in <sc_lv<AddressWidth> > address16;
sc_core::sc_in <sc_logic> ce16;
sc_core::sc_out <sc_lv<DataWidth> > q16;
sc_core::sc_in <sc_lv<AddressWidth> > address17;
sc_core::sc_in <sc_logic> ce17;
sc_core::sc_out <sc_lv<DataWidth> > q17;
sc_core::sc_in <sc_lv<AddressWidth> > address18;
sc_core::sc_in <sc_logic> ce18;
sc_core::sc_out <sc_lv<DataWidth> > q18;
sc_core::sc_in <sc_lv<AddressWidth> > address19;
sc_core::sc_in <sc_logic> ce19;
sc_core::sc_out <sc_lv<DataWidth> > q19;
sc_core::sc_in <sc_lv<AddressWidth> > address20;
sc_core::sc_in <sc_logic> ce20;
sc_core::sc_out <sc_lv<DataWidth> > q20;
sc_core::sc_in <sc_lv<AddressWidth> > address21;
sc_core::sc_in <sc_logic> ce21;
sc_core::sc_out <sc_lv<DataWidth> > q21;
sc_core::sc_in <sc_lv<AddressWidth> > address22;
sc_core::sc_in <sc_logic> ce22;
sc_core::sc_out <sc_lv<DataWidth> > q22;
sc_core::sc_in <sc_lv<AddressWidth> > address23;
sc_core::sc_in <sc_logic> ce23;
sc_core::sc_out <sc_lv<DataWidth> > q23;
sc_core::sc_in <sc_lv<AddressWidth> > address24;
sc_core::sc_in <sc_logic> ce24;
sc_core::sc_out <sc_lv<DataWidth> > q24;
sc_core::sc_in <sc_lv<AddressWidth> > address25;
sc_core::sc_in <sc_logic> ce25;
sc_core::sc_out <sc_lv<DataWidth> > q25;
sc_core::sc_in <sc_lv<AddressWidth> > address26;
sc_core::sc_in <sc_logic> ce26;
sc_core::sc_out <sc_lv<DataWidth> > q26;
sc_core::sc_in <sc_lv<AddressWidth> > address27;
sc_core::sc_in <sc_logic> ce27;
sc_core::sc_out <sc_lv<DataWidth> > q27;
sc_core::sc_in <sc_lv<AddressWidth> > address28;
sc_core::sc_in <sc_logic> ce28;
sc_core::sc_out <sc_lv<DataWidth> > q28;
sc_core::sc_in <sc_lv<AddressWidth> > address29;
sc_core::sc_in <sc_logic> ce29;
sc_core::sc_out <sc_lv<DataWidth> > q29;
sc_core::sc_in <sc_lv<AddressWidth> > address30;
sc_core::sc_in <sc_logic> ce30;
sc_core::sc_out <sc_lv<DataWidth> > q30;
sc_core::sc_in <sc_lv<AddressWidth> > address31;
sc_core::sc_in <sc_logic> ce31;
sc_core::sc_out <sc_lv<DataWidth> > q31;
sc_core::sc_in <sc_lv<AddressWidth> > address32;
sc_core::sc_in <sc_logic> ce32;
sc_core::sc_out <sc_lv<DataWidth> > q32;
sc_core::sc_in <sc_lv<AddressWidth> > address33;
sc_core::sc_in <sc_logic> ce33;
sc_core::sc_out <sc_lv<DataWidth> > q33;
sc_core::sc_in <sc_lv<AddressWidth> > address34;
sc_core::sc_in <sc_logic> ce34;
sc_core::sc_out <sc_lv<DataWidth> > q34;
sc_core::sc_in <sc_lv<AddressWidth> > address35;
sc_core::sc_in <sc_logic> ce35;
sc_core::sc_out <sc_lv<DataWidth> > q35;
sc_core::sc_in <sc_lv<AddressWidth> > address36;
sc_core::sc_in <sc_logic> ce36;
sc_core::sc_out <sc_lv<DataWidth> > q36;
sc_core::sc_in <sc_lv<AddressWidth> > address37;
sc_core::sc_in <sc_logic> ce37;
sc_core::sc_out <sc_lv<DataWidth> > q37;
sc_core::sc_in <sc_lv<AddressWidth> > address38;
sc_core::sc_in <sc_logic> ce38;
sc_core::sc_out <sc_lv<DataWidth> > q38;
sc_core::sc_in <sc_lv<AddressWidth> > address39;
sc_core::sc_in <sc_logic> ce39;
sc_core::sc_out <sc_lv<DataWidth> > q39;
sc_core::sc_in <sc_lv<AddressWidth> > address40;
sc_core::sc_in <sc_logic> ce40;
sc_core::sc_out <sc_lv<DataWidth> > q40;
sc_core::sc_in <sc_lv<AddressWidth> > address41;
sc_core::sc_in <sc_logic> ce41;
sc_core::sc_out <sc_lv<DataWidth> > q41;
sc_core::sc_in <sc_lv<AddressWidth> > address42;
sc_core::sc_in <sc_logic> ce42;
sc_core::sc_out <sc_lv<DataWidth> > q42;
sc_core::sc_in <sc_lv<AddressWidth> > address43;
sc_core::sc_in <sc_logic> ce43;
sc_core::sc_out <sc_lv<DataWidth> > q43;
sc_core::sc_in <sc_lv<AddressWidth> > address44;
sc_core::sc_in <sc_logic> ce44;
sc_core::sc_out <sc_lv<DataWidth> > q44;
sc_core::sc_in <sc_lv<AddressWidth> > address45;
sc_core::sc_in <sc_logic> ce45;
sc_core::sc_out <sc_lv<DataWidth> > q45;
sc_core::sc_in <sc_lv<AddressWidth> > address46;
sc_core::sc_in <sc_logic> ce46;
sc_core::sc_out <sc_lv<DataWidth> > q46;
sc_core::sc_in <sc_lv<AddressWidth> > address47;
sc_core::sc_in <sc_logic> ce47;
sc_core::sc_out <sc_lv<DataWidth> > q47;
sc_core::sc_in <sc_lv<AddressWidth> > address48;
sc_core::sc_in <sc_logic> ce48;
sc_core::sc_out <sc_lv<DataWidth> > q48;
sc_core::sc_in <sc_lv<AddressWidth> > address49;
sc_core::sc_in <sc_logic> ce49;
sc_core::sc_out <sc_lv<DataWidth> > q49;
sc_core::sc_in <sc_lv<AddressWidth> > address50;
sc_core::sc_in <sc_logic> ce50;
sc_core::sc_out <sc_lv<DataWidth> > q50;
sc_core::sc_in <sc_lv<AddressWidth> > address51;
sc_core::sc_in <sc_logic> ce51;
sc_core::sc_out <sc_lv<DataWidth> > q51;
sc_core::sc_in <sc_lv<AddressWidth> > address52;
sc_core::sc_in <sc_logic> ce52;
sc_core::sc_out <sc_lv<DataWidth> > q52;
sc_core::sc_in <sc_lv<AddressWidth> > address53;
sc_core::sc_in <sc_logic> ce53;
sc_core::sc_out <sc_lv<DataWidth> > q53;
sc_core::sc_in <sc_lv<AddressWidth> > address54;
sc_core::sc_in <sc_logic> ce54;
sc_core::sc_out <sc_lv<DataWidth> > q54;
sc_core::sc_in <sc_lv<AddressWidth> > address55;
sc_core::sc_in <sc_logic> ce55;
sc_core::sc_out <sc_lv<DataWidth> > q55;
sc_core::sc_in <sc_lv<AddressWidth> > address56;
sc_core::sc_in <sc_logic> ce56;
sc_core::sc_out <sc_lv<DataWidth> > q56;
sc_core::sc_in <sc_lv<AddressWidth> > address57;
sc_core::sc_in <sc_logic> ce57;
sc_core::sc_out <sc_lv<DataWidth> > q57;
sc_core::sc_in <sc_lv<AddressWidth> > address58;
sc_core::sc_in <sc_logic> ce58;
sc_core::sc_out <sc_lv<DataWidth> > q58;
sc_core::sc_in <sc_lv<AddressWidth> > address59;
sc_core::sc_in <sc_logic> ce59;
sc_core::sc_out <sc_lv<DataWidth> > q59;
sc_core::sc_in <sc_lv<AddressWidth> > address60;
sc_core::sc_in <sc_logic> ce60;
sc_core::sc_out <sc_lv<DataWidth> > q60;
sc_core::sc_in <sc_lv<AddressWidth> > address61;
sc_core::sc_in <sc_logic> ce61;
sc_core::sc_out <sc_lv<DataWidth> > q61;
sc_core::sc_in <sc_lv<AddressWidth> > address62;
sc_core::sc_in <sc_logic> ce62;
sc_core::sc_out <sc_lv<DataWidth> > q62;
sc_core::sc_in <sc_lv<AddressWidth> > address63;
sc_core::sc_in <sc_logic> ce63;
sc_core::sc_out <sc_lv<DataWidth> > q63;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(encrypt_128_key_ebkb_ram) {
        ram[0] = "0b01100011";
        ram[1] = "0b01100011";
        ram[2] = "0b10100101";
        ram[3] = "0b11000110";
        ram[4] = "0b01111100";
        ram[5] = "0b01111100";
        ram[6] = "0b10000100";
        ram[7] = "0b11111000";
        ram[8] = "0b01110111";
        ram[9] = "0b01110111";
        ram[10] = "0b10011001";
        ram[11] = "0b11101110";
        ram[12] = "0b01111011";
        ram[13] = "0b01111011";
        ram[14] = "0b10001101";
        ram[15] = "0b11110110";
        ram[16] = "0b11110010";
        ram[17] = "0b11110010";
        ram[18] = "0b00001101";
        ram[19] = "0b11111111";
        ram[20] = "0b01101011";
        ram[21] = "0b01101011";
        ram[22] = "0b10111101";
        ram[23] = "0b11010110";
        ram[24] = "0b01101111";
        ram[25] = "0b01101111";
        ram[26] = "0b10110001";
        ram[27] = "0b11011110";
        ram[28] = "0b11000101";
        ram[29] = "0b11000101";
        ram[30] = "0b01010100";
        ram[31] = "0b10010001";
        ram[32] = "0b00110000";
        ram[33] = "0b00110000";
        ram[34] = "0b01010000";
        ram[35] = "0b01100000";
        ram[36] = "0b00000001";
        ram[37] = "0b00000001";
        ram[38] = "0b00000011";
        ram[39] = "0b00000010";
        ram[40] = "0b01100111";
        ram[41] = "0b01100111";
        ram[42] = "0b10101001";
        ram[43] = "0b11001110";
        ram[44] = "0b00101011";
        ram[45] = "0b00101011";
        ram[46] = "0b01111101";
        ram[47] = "0b01010110";
        ram[48] = "0b11111110";
        ram[49] = "0b11111110";
        ram[50] = "0b00011001";
        ram[51] = "0b11100111";
        ram[52] = "0b11010111";
        ram[53] = "0b11010111";
        ram[54] = "0b01100010";
        ram[55] = "0b10110101";
        ram[56] = "0b10101011";
        ram[57] = "0b10101011";
        ram[58] = "0b11100110";
        ram[59] = "0b01001101";
        ram[60] = "0b01110110";
        ram[61] = "0b01110110";
        ram[62] = "0b10011010";
        ram[63] = "0b11101100";
        ram[64] = "0b11001010";
        ram[65] = "0b11001010";
        ram[66] = "0b01000101";
        ram[67] = "0b10001111";
        ram[68] = "0b10000010";
        ram[69] = "0b10000010";
        ram[70] = "0b10011101";
        ram[71] = "0b00011111";
        ram[72] = "0b11001001";
        ram[73] = "0b11001001";
        ram[74] = "0b01000000";
        ram[75] = "0b10001001";
        ram[76] = "0b01111101";
        ram[77] = "0b01111101";
        ram[78] = "0b10000111";
        ram[79] = "0b11111010";
        ram[80] = "0b11111010";
        ram[81] = "0b11111010";
        ram[82] = "0b00010101";
        ram[83] = "0b11101111";
        ram[84] = "0b01011001";
        ram[85] = "0b01011001";
        ram[86] = "0b11101011";
        ram[87] = "0b10110010";
        ram[88] = "0b01000111";
        ram[89] = "0b01000111";
        ram[90] = "0b11001001";
        ram[91] = "0b10001110";
        ram[92] = "0b11110000";
        ram[93] = "0b11110000";
        ram[94] = "0b00001011";
        ram[95] = "0b11111011";
        ram[96] = "0b10101101";
        ram[97] = "0b10101101";
        ram[98] = "0b11101100";
        ram[99] = "0b01000001";
        ram[100] = "0b11010100";
        ram[101] = "0b11010100";
        ram[102] = "0b01100111";
        ram[103] = "0b10110011";
        ram[104] = "0b10100010";
        ram[105] = "0b10100010";
        ram[106] = "0b11111101";
        ram[107] = "0b01011111";
        ram[108] = "0b10101111";
        ram[109] = "0b10101111";
        ram[110] = "0b11101010";
        ram[111] = "0b01000101";
        ram[112] = "0b10011100";
        ram[113] = "0b10011100";
        ram[114] = "0b10111111";
        ram[115] = "0b00100011";
        ram[116] = "0b10100100";
        ram[117] = "0b10100100";
        ram[118] = "0b11110111";
        ram[119] = "0b01010011";
        ram[120] = "0b01110010";
        ram[121] = "0b01110010";
        ram[122] = "0b10010110";
        ram[123] = "0b11100100";
        ram[124] = "0b11000000";
        ram[125] = "0b11000000";
        ram[126] = "0b01011011";
        ram[127] = "0b10011011";
        ram[128] = "0b10110111";
        ram[129] = "0b10110111";
        ram[130] = "0b11000010";
        ram[131] = "0b01110101";
        ram[132] = "0b11111101";
        ram[133] = "0b11111101";
        ram[134] = "0b00011100";
        ram[135] = "0b11100001";
        ram[136] = "0b10010011";
        ram[137] = "0b10010011";
        ram[138] = "0b10101110";
        ram[139] = "0b00111101";
        ram[140] = "0b00100110";
        ram[141] = "0b00100110";
        ram[142] = "0b01101010";
        ram[143] = "0b01001100";
        ram[144] = "0b00110110";
        ram[145] = "0b00110110";
        ram[146] = "0b01011010";
        ram[147] = "0b01101100";
        ram[148] = "0b00111111";
        ram[149] = "0b00111111";
        ram[150] = "0b01000001";
        ram[151] = "0b01111110";
        ram[152] = "0b11110111";
        ram[153] = "0b11110111";
        ram[154] = "0b00000010";
        ram[155] = "0b11110101";
        ram[156] = "0b11001100";
        ram[157] = "0b11001100";
        ram[158] = "0b01001111";
        ram[159] = "0b10000011";
        ram[160] = "0b00110100";
        ram[161] = "0b00110100";
        ram[162] = "0b01011100";
        ram[163] = "0b01101000";
        ram[164] = "0b10100101";
        ram[165] = "0b10100101";
        ram[166] = "0b11110100";
        ram[167] = "0b01010001";
        ram[168] = "0b11100101";
        ram[169] = "0b11100101";
        ram[170] = "0b00110100";
        ram[171] = "0b11010001";
        ram[172] = "0b11110001";
        ram[173] = "0b11110001";
        ram[174] = "0b00001000";
        ram[175] = "0b11111001";
        ram[176] = "0b01110001";
        ram[177] = "0b01110001";
        ram[178] = "0b10010011";
        ram[179] = "0b11100010";
        ram[180] = "0b11011000";
        ram[181] = "0b11011000";
        ram[182] = "0b01110011";
        ram[183] = "0b10101011";
        ram[184] = "0b00110001";
        ram[185] = "0b00110001";
        ram[186] = "0b01010011";
        ram[187] = "0b01100010";
        ram[188] = "0b00010101";
        ram[189] = "0b00010101";
        ram[190] = "0b00111111";
        ram[191] = "0b00101010";
        ram[192] = "0b00000100";
        ram[193] = "0b00000100";
        ram[194] = "0b00001100";
        ram[195] = "0b00001000";
        ram[196] = "0b11000111";
        ram[197] = "0b11000111";
        ram[198] = "0b01010010";
        ram[199] = "0b10010101";
        ram[200] = "0b00100011";
        ram[201] = "0b00100011";
        ram[202] = "0b01100101";
        ram[203] = "0b01000110";
        ram[204] = "0b11000011";
        ram[205] = "0b11000011";
        ram[206] = "0b01011110";
        ram[207] = "0b10011101";
        ram[208] = "0b00011000";
        ram[209] = "0b00011000";
        ram[210] = "0b00101000";
        ram[211] = "0b00110000";
        ram[212] = "0b10010110";
        ram[213] = "0b10010110";
        ram[214] = "0b10100001";
        ram[215] = "0b00110111";
        ram[216] = "0b00000101";
        ram[217] = "0b00000101";
        ram[218] = "0b00001111";
        ram[219] = "0b00001010";
        ram[220] = "0b10011010";
        ram[221] = "0b10011010";
        ram[222] = "0b10110101";
        ram[223] = "0b00101111";
        ram[224] = "0b00000111";
        ram[225] = "0b00000111";
        ram[226] = "0b00001001";
        ram[227] = "0b00001110";
        ram[228] = "0b00010010";
        ram[229] = "0b00010010";
        ram[230] = "0b00110110";
        ram[231] = "0b00100100";
        ram[232] = "0b10000000";
        ram[233] = "0b10000000";
        ram[234] = "0b10011011";
        ram[235] = "0b00011011";
        ram[236] = "0b11100010";
        ram[237] = "0b11100010";
        ram[238] = "0b00111101";
        ram[239] = "0b11011111";
        ram[240] = "0b11101011";
        ram[241] = "0b11101011";
        ram[242] = "0b00100110";
        ram[243] = "0b11001101";
        ram[244] = "0b00100111";
        ram[245] = "0b00100111";
        ram[246] = "0b01101001";
        ram[247] = "0b01001110";
        ram[248] = "0b10110010";
        ram[249] = "0b10110010";
        ram[250] = "0b11001101";
        ram[251] = "0b01111111";
        ram[252] = "0b01110101";
        ram[253] = "0b01110101";
        ram[254] = "0b10011111";
        ram[255] = "0b11101010";
        ram[256] = "0b00001001";
        ram[257] = "0b00001001";
        ram[258] = "0b00011011";
        ram[259] = "0b00010010";
        ram[260] = "0b10000011";
        ram[261] = "0b10000011";
        ram[262] = "0b10011110";
        ram[263] = "0b00011101";
        ram[264] = "0b00101100";
        ram[265] = "0b00101100";
        ram[266] = "0b01110100";
        ram[267] = "0b01011000";
        ram[268] = "0b00011010";
        ram[269] = "0b00011010";
        ram[270] = "0b00101110";
        ram[271] = "0b00110100";
        ram[272] = "0b00011011";
        ram[273] = "0b00011011";
        ram[274] = "0b00101101";
        ram[275] = "0b00110110";
        ram[276] = "0b01101110";
        ram[277] = "0b01101110";
        ram[278] = "0b10110010";
        ram[279] = "0b11011100";
        ram[280] = "0b01011010";
        ram[281] = "0b01011010";
        ram[282] = "0b11101110";
        ram[283] = "0b10110100";
        ram[284] = "0b10100000";
        ram[285] = "0b10100000";
        ram[286] = "0b11111011";
        ram[287] = "0b01011011";
        ram[288] = "0b01010010";
        ram[289] = "0b01010010";
        ram[290] = "0b11110110";
        ram[291] = "0b10100100";
        ram[292] = "0b00111011";
        ram[293] = "0b00111011";
        ram[294] = "0b01001101";
        ram[295] = "0b01110110";
        ram[296] = "0b11010110";
        ram[297] = "0b11010110";
        ram[298] = "0b01100001";
        ram[299] = "0b10110111";
        ram[300] = "0b10110011";
        ram[301] = "0b10110011";
        ram[302] = "0b11001110";
        ram[303] = "0b01111101";
        ram[304] = "0b00101001";
        ram[305] = "0b00101001";
        ram[306] = "0b01111011";
        ram[307] = "0b01010010";
        ram[308] = "0b11100011";
        ram[309] = "0b11100011";
        ram[310] = "0b00111110";
        ram[311] = "0b11011101";
        ram[312] = "0b00101111";
        ram[313] = "0b00101111";
        ram[314] = "0b01110001";
        ram[315] = "0b01011110";
        ram[316] = "0b10000100";
        ram[317] = "0b10000100";
        ram[318] = "0b10010111";
        ram[319] = "0b00010011";
        ram[320] = "0b01010011";
        ram[321] = "0b01010011";
        ram[322] = "0b11110101";
        ram[323] = "0b10100110";
        ram[324] = "0b11010001";
        ram[325] = "0b11010001";
        ram[326] = "0b01101000";
        ram[327] = "0b10111001";
        ram[328] = "0b00000000";
        ram[329] = "0b00000000";
        ram[330] = "0b00000000";
        ram[331] = "0b00000000";
        ram[332] = "0b11101101";
        ram[333] = "0b11101101";
        ram[334] = "0b00101100";
        ram[335] = "0b11000001";
        ram[336] = "0b00100000";
        ram[337] = "0b00100000";
        ram[338] = "0b01100000";
        ram[339] = "0b01000000";
        ram[340] = "0b11111100";
        ram[341] = "0b11111100";
        ram[342] = "0b00011111";
        ram[343] = "0b11100011";
        ram[344] = "0b10110001";
        ram[345] = "0b10110001";
        ram[346] = "0b11001000";
        ram[347] = "0b01111001";
        ram[348] = "0b01011011";
        ram[349] = "0b01011011";
        ram[350] = "0b11101101";
        ram[351] = "0b10110110";
        ram[352] = "0b01101010";
        ram[353] = "0b01101010";
        ram[354] = "0b10111110";
        ram[355] = "0b11010100";
        ram[356] = "0b11001011";
        ram[357] = "0b11001011";
        ram[358] = "0b01000110";
        ram[359] = "0b10001101";
        ram[360] = "0b10111110";
        ram[361] = "0b10111110";
        ram[362] = "0b11011001";
        ram[363] = "0b01100111";
        ram[364] = "0b00111001";
        ram[365] = "0b00111001";
        ram[366] = "0b01001011";
        ram[367] = "0b01110010";
        ram[368] = "0b01001010";
        ram[369] = "0b01001010";
        ram[370] = "0b11011110";
        ram[371] = "0b10010100";
        ram[372] = "0b01001100";
        ram[373] = "0b01001100";
        ram[374] = "0b11010100";
        ram[375] = "0b10011000";
        ram[376] = "0b01011000";
        ram[377] = "0b01011000";
        ram[378] = "0b11101000";
        ram[379] = "0b10110000";
        ram[380] = "0b11001111";
        ram[381] = "0b11001111";
        ram[382] = "0b01001010";
        ram[383] = "0b10000101";
        ram[384] = "0b11010000";
        ram[385] = "0b11010000";
        ram[386] = "0b01101011";
        ram[387] = "0b10111011";
        ram[388] = "0b11101111";
        ram[389] = "0b11101111";
        ram[390] = "0b00101010";
        ram[391] = "0b11000101";
        ram[392] = "0b10101010";
        ram[393] = "0b10101010";
        ram[394] = "0b11100101";
        ram[395] = "0b01001111";
        ram[396] = "0b11111011";
        ram[397] = "0b11111011";
        ram[398] = "0b00010110";
        ram[399] = "0b11101101";
        ram[400] = "0b01000011";
        ram[401] = "0b01000011";
        ram[402] = "0b11000101";
        ram[403] = "0b10000110";
        ram[404] = "0b01001101";
        ram[405] = "0b01001101";
        ram[406] = "0b11010111";
        ram[407] = "0b10011010";
        ram[408] = "0b00110011";
        ram[409] = "0b00110011";
        ram[410] = "0b01010101";
        ram[411] = "0b01100110";
        ram[412] = "0b10000101";
        ram[413] = "0b10000101";
        ram[414] = "0b10010100";
        ram[415] = "0b00010001";
        ram[416] = "0b01000101";
        ram[417] = "0b01000101";
        ram[418] = "0b11001111";
        ram[419] = "0b10001010";
        ram[420] = "0b11111001";
        ram[421] = "0b11111001";
        ram[422] = "0b00010000";
        ram[423] = "0b11101001";
        ram[424] = "0b00000010";
        ram[425] = "0b00000010";
        ram[426] = "0b00000110";
        ram[427] = "0b00000100";
        ram[428] = "0b01111111";
        ram[429] = "0b01111111";
        ram[430] = "0b10000001";
        ram[431] = "0b11111110";
        ram[432] = "0b01010000";
        ram[433] = "0b01010000";
        ram[434] = "0b11110000";
        ram[435] = "0b10100000";
        ram[436] = "0b00111100";
        ram[437] = "0b00111100";
        ram[438] = "0b01000100";
        ram[439] = "0b01111000";
        ram[440] = "0b10011111";
        ram[441] = "0b10011111";
        ram[442] = "0b10111010";
        ram[443] = "0b00100101";
        ram[444] = "0b10101000";
        ram[445] = "0b10101000";
        ram[446] = "0b11100011";
        ram[447] = "0b01001011";
        ram[448] = "0b01010001";
        ram[449] = "0b01010001";
        ram[450] = "0b11110011";
        ram[451] = "0b10100010";
        ram[452] = "0b10100011";
        ram[453] = "0b10100011";
        ram[454] = "0b11111110";
        ram[455] = "0b01011101";
        ram[456] = "0b01000000";
        ram[457] = "0b01000000";
        ram[458] = "0b11000000";
        ram[459] = "0b10000000";
        ram[460] = "0b10001111";
        ram[461] = "0b10001111";
        ram[462] = "0b10001010";
        ram[463] = "0b00000101";
        ram[464] = "0b10010010";
        ram[465] = "0b10010010";
        ram[466] = "0b10101101";
        ram[467] = "0b00111111";
        ram[468] = "0b10011101";
        ram[469] = "0b10011101";
        ram[470] = "0b10111100";
        ram[471] = "0b00100001";
        ram[472] = "0b00111000";
        ram[473] = "0b00111000";
        ram[474] = "0b01001000";
        ram[475] = "0b01110000";
        ram[476] = "0b11110101";
        ram[477] = "0b11110101";
        ram[478] = "0b00000100";
        ram[479] = "0b11110001";
        ram[480] = "0b10111100";
        ram[481] = "0b10111100";
        ram[482] = "0b11011111";
        ram[483] = "0b01100011";
        ram[484] = "0b10110110";
        ram[485] = "0b10110110";
        ram[486] = "0b11000001";
        ram[487] = "0b01110111";
        ram[488] = "0b11011010";
        ram[489] = "0b11011010";
        ram[490] = "0b01110101";
        ram[491] = "0b10101111";
        ram[492] = "0b00100001";
        ram[493] = "0b00100001";
        ram[494] = "0b01100011";
        ram[495] = "0b01000010";
        ram[496] = "0b00010000";
        ram[497] = "0b00010000";
        ram[498] = "0b00110000";
        ram[499] = "0b00100000";
        ram[500] = "0b11111111";
        ram[501] = "0b11111111";
        ram[502] = "0b00011010";
        ram[503] = "0b11100101";
        ram[504] = "0b11110011";
        ram[505] = "0b11110011";
        ram[506] = "0b00001110";
        ram[507] = "0b11111101";
        ram[508] = "0b11010010";
        ram[509] = "0b11010010";
        ram[510] = "0b01101101";
        ram[511] = "0b10111111";
        ram[512] = "0b11001101";
        ram[513] = "0b11001101";
        ram[514] = "0b01001100";
        ram[515] = "0b10000001";
        ram[516] = "0b00001100";
        ram[517] = "0b00001100";
        ram[518] = "0b00010100";
        ram[519] = "0b00011000";
        ram[520] = "0b00010011";
        ram[521] = "0b00010011";
        ram[522] = "0b00110101";
        ram[523] = "0b00100110";
        ram[524] = "0b11101100";
        ram[525] = "0b11101100";
        ram[526] = "0b00101111";
        ram[527] = "0b11000011";
        ram[528] = "0b01011111";
        ram[529] = "0b01011111";
        ram[530] = "0b11100001";
        ram[531] = "0b10111110";
        ram[532] = "0b10010111";
        ram[533] = "0b10010111";
        ram[534] = "0b10100010";
        ram[535] = "0b00110101";
        ram[536] = "0b01000100";
        ram[537] = "0b01000100";
        ram[538] = "0b11001100";
        ram[539] = "0b10001000";
        ram[540] = "0b00010111";
        ram[541] = "0b00010111";
        ram[542] = "0b00111001";
        ram[543] = "0b00101110";
        ram[544] = "0b11000100";
        ram[545] = "0b11000100";
        ram[546] = "0b01010111";
        ram[547] = "0b10010011";
        ram[548] = "0b10100111";
        ram[549] = "0b10100111";
        ram[550] = "0b11110010";
        ram[551] = "0b01010101";
        ram[552] = "0b01111110";
        ram[553] = "0b01111110";
        ram[554] = "0b10000010";
        ram[555] = "0b11111100";
        ram[556] = "0b00111101";
        ram[557] = "0b00111101";
        ram[558] = "0b01000111";
        ram[559] = "0b01111010";
        ram[560] = "0b01100100";
        ram[561] = "0b01100100";
        ram[562] = "0b10101100";
        ram[563] = "0b11001000";
        ram[564] = "0b01011101";
        ram[565] = "0b01011101";
        ram[566] = "0b11100111";
        ram[567] = "0b10111010";
        ram[568] = "0b00011001";
        ram[569] = "0b00011001";
        ram[570] = "0b00101011";
        ram[571] = "0b00110010";
        ram[572] = "0b01110011";
        ram[573] = "0b01110011";
        ram[574] = "0b10010101";
        ram[575] = "0b11100110";
        ram[576] = "0b01100000";
        ram[577] = "0b01100000";
        ram[578] = "0b10100000";
        ram[579] = "0b11000000";
        ram[580] = "0b10000001";
        ram[581] = "0b10000001";
        ram[582] = "0b10011000";
        ram[583] = "0b00011001";
        ram[584] = "0b01001111";
        ram[585] = "0b01001111";
        ram[586] = "0b11010001";
        ram[587] = "0b10011110";
        ram[588] = "0b11011100";
        ram[589] = "0b11011100";
        ram[590] = "0b01111111";
        ram[591] = "0b10100011";
        ram[592] = "0b00100010";
        ram[593] = "0b00100010";
        ram[594] = "0b01100110";
        ram[595] = "0b01000100";
        ram[596] = "0b00101010";
        ram[597] = "0b00101010";
        ram[598] = "0b01111110";
        ram[599] = "0b01010100";
        ram[600] = "0b10010000";
        ram[601] = "0b10010000";
        ram[602] = "0b10101011";
        ram[603] = "0b00111011";
        ram[604] = "0b10001000";
        ram[605] = "0b10001000";
        ram[606] = "0b10000011";
        ram[607] = "0b00001011";
        ram[608] = "0b01000110";
        ram[609] = "0b01000110";
        ram[610] = "0b11001010";
        ram[611] = "0b10001100";
        ram[612] = "0b11101110";
        ram[613] = "0b11101110";
        ram[614] = "0b00101001";
        ram[615] = "0b11000111";
        ram[616] = "0b10111000";
        ram[617] = "0b10111000";
        ram[618] = "0b11010011";
        ram[619] = "0b01101011";
        ram[620] = "0b00010100";
        ram[621] = "0b00010100";
        ram[622] = "0b00111100";
        ram[623] = "0b00101000";
        ram[624] = "0b11011110";
        ram[625] = "0b11011110";
        ram[626] = "0b01111001";
        ram[627] = "0b10100111";
        ram[628] = "0b01011110";
        ram[629] = "0b01011110";
        ram[630] = "0b11100010";
        ram[631] = "0b10111100";
        ram[632] = "0b00001011";
        ram[633] = "0b00001011";
        ram[634] = "0b00011101";
        ram[635] = "0b00010110";
        ram[636] = "0b11011011";
        ram[637] = "0b11011011";
        ram[638] = "0b01110110";
        ram[639] = "0b10101101";
        ram[640] = "0b11100000";
        ram[641] = "0b11100000";
        ram[642] = "0b00111011";
        ram[643] = "0b11011011";
        ram[644] = "0b00110010";
        ram[645] = "0b00110010";
        ram[646] = "0b01010110";
        ram[647] = "0b01100100";
        ram[648] = "0b00111010";
        ram[649] = "0b00111010";
        ram[650] = "0b01001110";
        ram[651] = "0b01110100";
        ram[652] = "0b00001010";
        ram[653] = "0b00001010";
        ram[654] = "0b00011110";
        ram[655] = "0b00010100";
        ram[656] = "0b01001001";
        ram[657] = "0b01001001";
        ram[658] = "0b11011011";
        ram[659] = "0b10010010";
        ram[660] = "0b00000110";
        ram[661] = "0b00000110";
        ram[662] = "0b00001010";
        ram[663] = "0b00001100";
        ram[664] = "0b00100100";
        ram[665] = "0b00100100";
        ram[666] = "0b01101100";
        ram[667] = "0b01001000";
        ram[668] = "0b01011100";
        ram[669] = "0b01011100";
        ram[670] = "0b11100100";
        ram[671] = "0b10111000";
        ram[672] = "0b11000010";
        ram[673] = "0b11000010";
        ram[674] = "0b01011101";
        ram[675] = "0b10011111";
        ram[676] = "0b11010011";
        ram[677] = "0b11010011";
        ram[678] = "0b01101110";
        ram[679] = "0b10111101";
        ram[680] = "0b10101100";
        ram[681] = "0b10101100";
        ram[682] = "0b11101111";
        ram[683] = "0b01000011";
        ram[684] = "0b01100010";
        ram[685] = "0b01100010";
        ram[686] = "0b10100110";
        ram[687] = "0b11000100";
        ram[688] = "0b10010001";
        ram[689] = "0b10010001";
        ram[690] = "0b10101000";
        ram[691] = "0b00111001";
        ram[692] = "0b10010101";
        ram[693] = "0b10010101";
        ram[694] = "0b10100100";
        ram[695] = "0b00110001";
        ram[696] = "0b11100100";
        ram[697] = "0b11100100";
        ram[698] = "0b00110111";
        ram[699] = "0b11010011";
        ram[700] = "0b01111001";
        ram[701] = "0b01111001";
        ram[702] = "0b10001011";
        ram[703] = "0b11110010";
        ram[704] = "0b11100111";
        ram[705] = "0b11100111";
        ram[706] = "0b00110010";
        ram[707] = "0b11010101";
        ram[708] = "0b11001000";
        ram[709] = "0b11001000";
        ram[710] = "0b01000011";
        ram[711] = "0b10001011";
        ram[712] = "0b00110111";
        ram[713] = "0b00110111";
        ram[714] = "0b01011001";
        ram[715] = "0b01101110";
        ram[716] = "0b01101101";
        ram[717] = "0b01101101";
        ram[718] = "0b10110111";
        ram[719] = "0b11011010";
        ram[720] = "0b10001101";
        ram[721] = "0b10001101";
        ram[722] = "0b10001100";
        ram[723] = "0b00000001";
        ram[724] = "0b11010101";
        ram[725] = "0b11010101";
        ram[726] = "0b01100100";
        ram[727] = "0b10110001";
        ram[728] = "0b01001110";
        ram[729] = "0b01001110";
        ram[730] = "0b11010010";
        ram[731] = "0b10011100";
        ram[732] = "0b10101001";
        ram[733] = "0b10101001";
        ram[734] = "0b11100000";
        ram[735] = "0b01001001";
        ram[736] = "0b01101100";
        ram[737] = "0b01101100";
        ram[738] = "0b10110100";
        ram[739] = "0b11011000";
        ram[740] = "0b01010110";
        ram[741] = "0b01010110";
        ram[742] = "0b11111010";
        ram[743] = "0b10101100";
        ram[744] = "0b11110100";
        ram[745] = "0b11110100";
        ram[746] = "0b00000111";
        ram[747] = "0b11110011";
        ram[748] = "0b11101010";
        ram[749] = "0b11101010";
        ram[750] = "0b00100101";
        ram[751] = "0b11001111";
        ram[752] = "0b01100101";
        ram[753] = "0b01100101";
        ram[754] = "0b10101111";
        ram[755] = "0b11001010";
        ram[756] = "0b01111010";
        ram[757] = "0b01111010";
        ram[758] = "0b10001110";
        ram[759] = "0b11110100";
        ram[760] = "0b10101110";
        ram[761] = "0b10101110";
        ram[762] = "0b11101001";
        ram[763] = "0b01000111";
        ram[764] = "0b00001000";
        ram[765] = "0b00001000";
        ram[766] = "0b00011000";
        ram[767] = "0b00010000";
        ram[768] = "0b10111010";
        ram[769] = "0b10111010";
        ram[770] = "0b11010101";
        ram[771] = "0b01101111";
        ram[772] = "0b01111000";
        ram[773] = "0b01111000";
        ram[774] = "0b10001000";
        ram[775] = "0b11110000";
        ram[776] = "0b00100101";
        ram[777] = "0b00100101";
        ram[778] = "0b01101111";
        ram[779] = "0b01001010";
        ram[780] = "0b00101110";
        ram[781] = "0b00101110";
        ram[782] = "0b01110010";
        ram[783] = "0b01011100";
        ram[784] = "0b00011100";
        ram[785] = "0b00011100";
        ram[786] = "0b00100100";
        ram[787] = "0b00111000";
        ram[788] = "0b10100110";
        ram[789] = "0b10100110";
        ram[790] = "0b11110001";
        ram[791] = "0b01010111";
        ram[792] = "0b10110100";
        ram[793] = "0b10110100";
        ram[794] = "0b11000111";
        ram[795] = "0b01110011";
        ram[796] = "0b11000110";
        ram[797] = "0b11000110";
        ram[798] = "0b01010001";
        ram[799] = "0b10010111";
        ram[800] = "0b11101000";
        ram[801] = "0b11101000";
        ram[802] = "0b00100011";
        ram[803] = "0b11001011";
        ram[804] = "0b11011101";
        ram[805] = "0b11011101";
        ram[806] = "0b01111100";
        ram[807] = "0b10100001";
        ram[808] = "0b01110100";
        ram[809] = "0b01110100";
        ram[810] = "0b10011100";
        ram[811] = "0b11101000";
        ram[812] = "0b00011111";
        ram[813] = "0b00011111";
        ram[814] = "0b00100001";
        ram[815] = "0b00111110";
        ram[816] = "0b01001011";
        ram[817] = "0b01001011";
        ram[818] = "0b11011101";
        ram[819] = "0b10010110";
        ram[820] = "0b10111101";
        ram[821] = "0b10111101";
        ram[822] = "0b11011100";
        ram[823] = "0b01100001";
        ram[824] = "0b10001011";
        ram[825] = "0b10001011";
        ram[826] = "0b10000110";
        ram[827] = "0b00001101";
        ram[828] = "0b10001010";
        ram[829] = "0b10001010";
        ram[830] = "0b10000101";
        ram[831] = "0b00001111";
        ram[832] = "0b01110000";
        ram[833] = "0b01110000";
        ram[834] = "0b10010000";
        ram[835] = "0b11100000";
        ram[836] = "0b00111110";
        ram[837] = "0b00111110";
        ram[838] = "0b01000010";
        ram[839] = "0b01111100";
        ram[840] = "0b10110101";
        ram[841] = "0b10110101";
        ram[842] = "0b11000100";
        ram[843] = "0b01110001";
        ram[844] = "0b01100110";
        ram[845] = "0b01100110";
        ram[846] = "0b10101010";
        ram[847] = "0b11001100";
        ram[848] = "0b01001000";
        ram[849] = "0b01001000";
        ram[850] = "0b11011000";
        ram[851] = "0b10010000";
        ram[852] = "0b00000011";
        ram[853] = "0b00000011";
        ram[854] = "0b00000101";
        ram[855] = "0b00000110";
        ram[856] = "0b11110110";
        ram[857] = "0b11110110";
        ram[858] = "0b00000001";
        ram[859] = "0b11110111";
        ram[860] = "0b00001110";
        ram[861] = "0b00001110";
        ram[862] = "0b00010010";
        ram[863] = "0b00011100";
        ram[864] = "0b01100001";
        ram[865] = "0b01100001";
        ram[866] = "0b10100011";
        ram[867] = "0b11000010";
        ram[868] = "0b00110101";
        ram[869] = "0b00110101";
        ram[870] = "0b01011111";
        ram[871] = "0b01101010";
        ram[872] = "0b01010111";
        ram[873] = "0b01010111";
        ram[874] = "0b11111001";
        ram[875] = "0b10101110";
        ram[876] = "0b10111001";
        ram[877] = "0b10111001";
        ram[878] = "0b11010000";
        ram[879] = "0b01101001";
        ram[880] = "0b10000110";
        ram[881] = "0b10000110";
        ram[882] = "0b10010001";
        ram[883] = "0b00010111";
        ram[884] = "0b11000001";
        ram[885] = "0b11000001";
        ram[886] = "0b01011000";
        ram[887] = "0b10011001";
        ram[888] = "0b00011101";
        ram[889] = "0b00011101";
        ram[890] = "0b00100111";
        ram[891] = "0b00111010";
        ram[892] = "0b10011110";
        ram[893] = "0b10011110";
        ram[894] = "0b10111001";
        ram[895] = "0b00100111";
        ram[896] = "0b11100001";
        ram[897] = "0b11100001";
        ram[898] = "0b00111000";
        ram[899] = "0b11011001";
        ram[900] = "0b11111000";
        ram[901] = "0b11111000";
        ram[902] = "0b00010011";
        ram[903] = "0b11101011";
        ram[904] = "0b10011000";
        ram[905] = "0b10011000";
        ram[906] = "0b10110011";
        ram[907] = "0b00101011";
        ram[908] = "0b00010001";
        ram[909] = "0b00010001";
        ram[910] = "0b00110011";
        ram[911] = "0b00100010";
        ram[912] = "0b01101001";
        ram[913] = "0b01101001";
        ram[914] = "0b10111011";
        ram[915] = "0b11010010";
        ram[916] = "0b11011001";
        ram[917] = "0b11011001";
        ram[918] = "0b01110000";
        ram[919] = "0b10101001";
        ram[920] = "0b10001110";
        ram[921] = "0b10001110";
        ram[922] = "0b10001001";
        ram[923] = "0b00000111";
        ram[924] = "0b10010100";
        ram[925] = "0b10010100";
        ram[926] = "0b10100111";
        ram[927] = "0b00110011";
        ram[928] = "0b10011011";
        ram[929] = "0b10011011";
        ram[930] = "0b10110110";
        ram[931] = "0b00101101";
        ram[932] = "0b00011110";
        ram[933] = "0b00011110";
        ram[934] = "0b00100010";
        ram[935] = "0b00111100";
        ram[936] = "0b10000111";
        ram[937] = "0b10000111";
        ram[938] = "0b10010010";
        ram[939] = "0b00010101";
        ram[940] = "0b11101001";
        ram[941] = "0b11101001";
        ram[942] = "0b00100000";
        ram[943] = "0b11001001";
        ram[944] = "0b11001110";
        ram[945] = "0b11001110";
        ram[946] = "0b01001001";
        ram[947] = "0b10000111";
        ram[948] = "0b01010101";
        ram[949] = "0b01010101";
        ram[950] = "0b11111111";
        ram[951] = "0b10101010";
        ram[952] = "0b00101000";
        ram[953] = "0b00101000";
        ram[954] = "0b01111000";
        ram[955] = "0b01010000";
        ram[956] = "0b11011111";
        ram[957] = "0b11011111";
        ram[958] = "0b01111010";
        ram[959] = "0b10100101";
        ram[960] = "0b10001100";
        ram[961] = "0b10001100";
        ram[962] = "0b10001111";
        ram[963] = "0b00000011";
        ram[964] = "0b10100001";
        ram[965] = "0b10100001";
        ram[966] = "0b11111000";
        ram[967] = "0b01011001";
        ram[968] = "0b10001001";
        ram[969] = "0b10001001";
        ram[970] = "0b10000000";
        ram[971] = "0b00001001";
        ram[972] = "0b00001101";
        ram[973] = "0b00001101";
        ram[974] = "0b00010111";
        ram[975] = "0b00011010";
        ram[976] = "0b10111111";
        ram[977] = "0b10111111";
        ram[978] = "0b11011010";
        ram[979] = "0b01100101";
        ram[980] = "0b11100110";
        ram[981] = "0b11100110";
        ram[982] = "0b00110001";
        ram[983] = "0b11010111";
        ram[984] = "0b01000010";
        ram[985] = "0b01000010";
        ram[986] = "0b11000110";
        ram[987] = "0b10000100";
        ram[988] = "0b01101000";
        ram[989] = "0b01101000";
        ram[990] = "0b10111000";
        ram[991] = "0b11010000";
        ram[992] = "0b01000001";
        ram[993] = "0b01000001";
        ram[994] = "0b11000011";
        ram[995] = "0b10000010";
        ram[996] = "0b10011001";
        ram[997] = "0b10011001";
        ram[998] = "0b10110000";
        ram[999] = "0b00101001";
        ram[1000] = "0b00101101";
        ram[1001] = "0b00101101";
        ram[1002] = "0b01110111";
        ram[1003] = "0b01011010";
        ram[1004] = "0b00001111";
        ram[1005] = "0b00001111";
        ram[1006] = "0b00010001";
        ram[1007] = "0b00011110";
        ram[1008] = "0b10110000";
        ram[1009] = "0b10110000";
        ram[1010] = "0b11001011";
        ram[1011] = "0b01111011";
        ram[1012] = "0b01010100";
        ram[1013] = "0b01010100";
        ram[1014] = "0b11111100";
        ram[1015] = "0b10101000";
        ram[1016] = "0b10111011";
        ram[1017] = "0b10111011";
        ram[1018] = "0b11010110";
        ram[1019] = "0b01101101";
        ram[1020] = "0b00010110";
        ram[1021] = "0b00010110";
        ram[1022] = "0b00111010";
        ram[1023] = "0b00101100";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();


SC_METHOD(prc_write_1);
  sensitive<<clk.pos();


SC_METHOD(prc_write_2);
  sensitive<<clk.pos();


SC_METHOD(prc_write_3);
  sensitive<<clk.pos();


SC_METHOD(prc_write_4);
  sensitive<<clk.pos();


SC_METHOD(prc_write_5);
  sensitive<<clk.pos();


SC_METHOD(prc_write_6);
  sensitive<<clk.pos();


SC_METHOD(prc_write_7);
  sensitive<<clk.pos();


SC_METHOD(prc_write_8);
  sensitive<<clk.pos();


SC_METHOD(prc_write_9);
  sensitive<<clk.pos();


SC_METHOD(prc_write_10);
  sensitive<<clk.pos();


SC_METHOD(prc_write_11);
  sensitive<<clk.pos();


SC_METHOD(prc_write_12);
  sensitive<<clk.pos();


SC_METHOD(prc_write_13);
  sensitive<<clk.pos();


SC_METHOD(prc_write_14);
  sensitive<<clk.pos();


SC_METHOD(prc_write_15);
  sensitive<<clk.pos();


SC_METHOD(prc_write_16);
  sensitive<<clk.pos();


SC_METHOD(prc_write_17);
  sensitive<<clk.pos();


SC_METHOD(prc_write_18);
  sensitive<<clk.pos();


SC_METHOD(prc_write_19);
  sensitive<<clk.pos();


SC_METHOD(prc_write_20);
  sensitive<<clk.pos();


SC_METHOD(prc_write_21);
  sensitive<<clk.pos();


SC_METHOD(prc_write_22);
  sensitive<<clk.pos();


SC_METHOD(prc_write_23);
  sensitive<<clk.pos();


SC_METHOD(prc_write_24);
  sensitive<<clk.pos();


SC_METHOD(prc_write_25);
  sensitive<<clk.pos();


SC_METHOD(prc_write_26);
  sensitive<<clk.pos();


SC_METHOD(prc_write_27);
  sensitive<<clk.pos();


SC_METHOD(prc_write_28);
  sensitive<<clk.pos();


SC_METHOD(prc_write_29);
  sensitive<<clk.pos();


SC_METHOD(prc_write_30);
  sensitive<<clk.pos();


SC_METHOD(prc_write_31);
  sensitive<<clk.pos();


SC_METHOD(prc_write_32);
  sensitive<<clk.pos();


SC_METHOD(prc_write_33);
  sensitive<<clk.pos();


SC_METHOD(prc_write_34);
  sensitive<<clk.pos();


SC_METHOD(prc_write_35);
  sensitive<<clk.pos();


SC_METHOD(prc_write_36);
  sensitive<<clk.pos();


SC_METHOD(prc_write_37);
  sensitive<<clk.pos();


SC_METHOD(prc_write_38);
  sensitive<<clk.pos();


SC_METHOD(prc_write_39);
  sensitive<<clk.pos();


SC_METHOD(prc_write_40);
  sensitive<<clk.pos();


SC_METHOD(prc_write_41);
  sensitive<<clk.pos();


SC_METHOD(prc_write_42);
  sensitive<<clk.pos();


SC_METHOD(prc_write_43);
  sensitive<<clk.pos();


SC_METHOD(prc_write_44);
  sensitive<<clk.pos();


SC_METHOD(prc_write_45);
  sensitive<<clk.pos();


SC_METHOD(prc_write_46);
  sensitive<<clk.pos();


SC_METHOD(prc_write_47);
  sensitive<<clk.pos();


SC_METHOD(prc_write_48);
  sensitive<<clk.pos();


SC_METHOD(prc_write_49);
  sensitive<<clk.pos();


SC_METHOD(prc_write_50);
  sensitive<<clk.pos();


SC_METHOD(prc_write_51);
  sensitive<<clk.pos();


SC_METHOD(prc_write_52);
  sensitive<<clk.pos();


SC_METHOD(prc_write_53);
  sensitive<<clk.pos();


SC_METHOD(prc_write_54);
  sensitive<<clk.pos();


SC_METHOD(prc_write_55);
  sensitive<<clk.pos();


SC_METHOD(prc_write_56);
  sensitive<<clk.pos();


SC_METHOD(prc_write_57);
  sensitive<<clk.pos();


SC_METHOD(prc_write_58);
  sensitive<<clk.pos();


SC_METHOD(prc_write_59);
  sensitive<<clk.pos();


SC_METHOD(prc_write_60);
  sensitive<<clk.pos();


SC_METHOD(prc_write_61);
  sensitive<<clk.pos();


SC_METHOD(prc_write_62);
  sensitive<<clk.pos();


SC_METHOD(prc_write_63);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


void prc_write_1()
{
    if (ce1.read() == sc_dt::Log_1) 
    {
            if(address1.read().is_01() && address1.read().to_uint()<AddressRange)
              q1 = ram[address1.read().to_uint()];
            else
              q1 = sc_lv<DataWidth>();
    }
}


void prc_write_2()
{
    if (ce2.read() == sc_dt::Log_1) 
    {
            if(address2.read().is_01() && address2.read().to_uint()<AddressRange)
              q2 = ram[address2.read().to_uint()];
            else
              q2 = sc_lv<DataWidth>();
    }
}


void prc_write_3()
{
    if (ce3.read() == sc_dt::Log_1) 
    {
            if(address3.read().is_01() && address3.read().to_uint()<AddressRange)
              q3 = ram[address3.read().to_uint()];
            else
              q3 = sc_lv<DataWidth>();
    }
}


void prc_write_4()
{
    if (ce4.read() == sc_dt::Log_1) 
    {
            if(address4.read().is_01() && address4.read().to_uint()<AddressRange)
              q4 = ram[address4.read().to_uint()];
            else
              q4 = sc_lv<DataWidth>();
    }
}


void prc_write_5()
{
    if (ce5.read() == sc_dt::Log_1) 
    {
            if(address5.read().is_01() && address5.read().to_uint()<AddressRange)
              q5 = ram[address5.read().to_uint()];
            else
              q5 = sc_lv<DataWidth>();
    }
}


void prc_write_6()
{
    if (ce6.read() == sc_dt::Log_1) 
    {
            if(address6.read().is_01() && address6.read().to_uint()<AddressRange)
              q6 = ram[address6.read().to_uint()];
            else
              q6 = sc_lv<DataWidth>();
    }
}


void prc_write_7()
{
    if (ce7.read() == sc_dt::Log_1) 
    {
            if(address7.read().is_01() && address7.read().to_uint()<AddressRange)
              q7 = ram[address7.read().to_uint()];
            else
              q7 = sc_lv<DataWidth>();
    }
}


void prc_write_8()
{
    if (ce8.read() == sc_dt::Log_1) 
    {
            if(address8.read().is_01() && address8.read().to_uint()<AddressRange)
              q8 = ram[address8.read().to_uint()];
            else
              q8 = sc_lv<DataWidth>();
    }
}


void prc_write_9()
{
    if (ce9.read() == sc_dt::Log_1) 
    {
            if(address9.read().is_01() && address9.read().to_uint()<AddressRange)
              q9 = ram[address9.read().to_uint()];
            else
              q9 = sc_lv<DataWidth>();
    }
}


void prc_write_10()
{
    if (ce10.read() == sc_dt::Log_1) 
    {
            if(address10.read().is_01() && address10.read().to_uint()<AddressRange)
              q10 = ram[address10.read().to_uint()];
            else
              q10 = sc_lv<DataWidth>();
    }
}


void prc_write_11()
{
    if (ce11.read() == sc_dt::Log_1) 
    {
            if(address11.read().is_01() && address11.read().to_uint()<AddressRange)
              q11 = ram[address11.read().to_uint()];
            else
              q11 = sc_lv<DataWidth>();
    }
}


void prc_write_12()
{
    if (ce12.read() == sc_dt::Log_1) 
    {
            if(address12.read().is_01() && address12.read().to_uint()<AddressRange)
              q12 = ram[address12.read().to_uint()];
            else
              q12 = sc_lv<DataWidth>();
    }
}


void prc_write_13()
{
    if (ce13.read() == sc_dt::Log_1) 
    {
            if(address13.read().is_01() && address13.read().to_uint()<AddressRange)
              q13 = ram[address13.read().to_uint()];
            else
              q13 = sc_lv<DataWidth>();
    }
}


void prc_write_14()
{
    if (ce14.read() == sc_dt::Log_1) 
    {
            if(address14.read().is_01() && address14.read().to_uint()<AddressRange)
              q14 = ram[address14.read().to_uint()];
            else
              q14 = sc_lv<DataWidth>();
    }
}


void prc_write_15()
{
    if (ce15.read() == sc_dt::Log_1) 
    {
            if(address15.read().is_01() && address15.read().to_uint()<AddressRange)
              q15 = ram[address15.read().to_uint()];
            else
              q15 = sc_lv<DataWidth>();
    }
}


void prc_write_16()
{
    if (ce16.read() == sc_dt::Log_1) 
    {
            if(address16.read().is_01() && address16.read().to_uint()<AddressRange)
              q16 = ram[address16.read().to_uint()];
            else
              q16 = sc_lv<DataWidth>();
    }
}


void prc_write_17()
{
    if (ce17.read() == sc_dt::Log_1) 
    {
            if(address17.read().is_01() && address17.read().to_uint()<AddressRange)
              q17 = ram[address17.read().to_uint()];
            else
              q17 = sc_lv<DataWidth>();
    }
}


void prc_write_18()
{
    if (ce18.read() == sc_dt::Log_1) 
    {
            if(address18.read().is_01() && address18.read().to_uint()<AddressRange)
              q18 = ram[address18.read().to_uint()];
            else
              q18 = sc_lv<DataWidth>();
    }
}


void prc_write_19()
{
    if (ce19.read() == sc_dt::Log_1) 
    {
            if(address19.read().is_01() && address19.read().to_uint()<AddressRange)
              q19 = ram[address19.read().to_uint()];
            else
              q19 = sc_lv<DataWidth>();
    }
}


void prc_write_20()
{
    if (ce20.read() == sc_dt::Log_1) 
    {
            if(address20.read().is_01() && address20.read().to_uint()<AddressRange)
              q20 = ram[address20.read().to_uint()];
            else
              q20 = sc_lv<DataWidth>();
    }
}


void prc_write_21()
{
    if (ce21.read() == sc_dt::Log_1) 
    {
            if(address21.read().is_01() && address21.read().to_uint()<AddressRange)
              q21 = ram[address21.read().to_uint()];
            else
              q21 = sc_lv<DataWidth>();
    }
}


void prc_write_22()
{
    if (ce22.read() == sc_dt::Log_1) 
    {
            if(address22.read().is_01() && address22.read().to_uint()<AddressRange)
              q22 = ram[address22.read().to_uint()];
            else
              q22 = sc_lv<DataWidth>();
    }
}


void prc_write_23()
{
    if (ce23.read() == sc_dt::Log_1) 
    {
            if(address23.read().is_01() && address23.read().to_uint()<AddressRange)
              q23 = ram[address23.read().to_uint()];
            else
              q23 = sc_lv<DataWidth>();
    }
}


void prc_write_24()
{
    if (ce24.read() == sc_dt::Log_1) 
    {
            if(address24.read().is_01() && address24.read().to_uint()<AddressRange)
              q24 = ram[address24.read().to_uint()];
            else
              q24 = sc_lv<DataWidth>();
    }
}


void prc_write_25()
{
    if (ce25.read() == sc_dt::Log_1) 
    {
            if(address25.read().is_01() && address25.read().to_uint()<AddressRange)
              q25 = ram[address25.read().to_uint()];
            else
              q25 = sc_lv<DataWidth>();
    }
}


void prc_write_26()
{
    if (ce26.read() == sc_dt::Log_1) 
    {
            if(address26.read().is_01() && address26.read().to_uint()<AddressRange)
              q26 = ram[address26.read().to_uint()];
            else
              q26 = sc_lv<DataWidth>();
    }
}


void prc_write_27()
{
    if (ce27.read() == sc_dt::Log_1) 
    {
            if(address27.read().is_01() && address27.read().to_uint()<AddressRange)
              q27 = ram[address27.read().to_uint()];
            else
              q27 = sc_lv<DataWidth>();
    }
}


void prc_write_28()
{
    if (ce28.read() == sc_dt::Log_1) 
    {
            if(address28.read().is_01() && address28.read().to_uint()<AddressRange)
              q28 = ram[address28.read().to_uint()];
            else
              q28 = sc_lv<DataWidth>();
    }
}


void prc_write_29()
{
    if (ce29.read() == sc_dt::Log_1) 
    {
            if(address29.read().is_01() && address29.read().to_uint()<AddressRange)
              q29 = ram[address29.read().to_uint()];
            else
              q29 = sc_lv<DataWidth>();
    }
}


void prc_write_30()
{
    if (ce30.read() == sc_dt::Log_1) 
    {
            if(address30.read().is_01() && address30.read().to_uint()<AddressRange)
              q30 = ram[address30.read().to_uint()];
            else
              q30 = sc_lv<DataWidth>();
    }
}


void prc_write_31()
{
    if (ce31.read() == sc_dt::Log_1) 
    {
            if(address31.read().is_01() && address31.read().to_uint()<AddressRange)
              q31 = ram[address31.read().to_uint()];
            else
              q31 = sc_lv<DataWidth>();
    }
}


void prc_write_32()
{
    if (ce32.read() == sc_dt::Log_1) 
    {
            if(address32.read().is_01() && address32.read().to_uint()<AddressRange)
              q32 = ram[address32.read().to_uint()];
            else
              q32 = sc_lv<DataWidth>();
    }
}


void prc_write_33()
{
    if (ce33.read() == sc_dt::Log_1) 
    {
            if(address33.read().is_01() && address33.read().to_uint()<AddressRange)
              q33 = ram[address33.read().to_uint()];
            else
              q33 = sc_lv<DataWidth>();
    }
}


void prc_write_34()
{
    if (ce34.read() == sc_dt::Log_1) 
    {
            if(address34.read().is_01() && address34.read().to_uint()<AddressRange)
              q34 = ram[address34.read().to_uint()];
            else
              q34 = sc_lv<DataWidth>();
    }
}


void prc_write_35()
{
    if (ce35.read() == sc_dt::Log_1) 
    {
            if(address35.read().is_01() && address35.read().to_uint()<AddressRange)
              q35 = ram[address35.read().to_uint()];
            else
              q35 = sc_lv<DataWidth>();
    }
}


void prc_write_36()
{
    if (ce36.read() == sc_dt::Log_1) 
    {
            if(address36.read().is_01() && address36.read().to_uint()<AddressRange)
              q36 = ram[address36.read().to_uint()];
            else
              q36 = sc_lv<DataWidth>();
    }
}


void prc_write_37()
{
    if (ce37.read() == sc_dt::Log_1) 
    {
            if(address37.read().is_01() && address37.read().to_uint()<AddressRange)
              q37 = ram[address37.read().to_uint()];
            else
              q37 = sc_lv<DataWidth>();
    }
}


void prc_write_38()
{
    if (ce38.read() == sc_dt::Log_1) 
    {
            if(address38.read().is_01() && address38.read().to_uint()<AddressRange)
              q38 = ram[address38.read().to_uint()];
            else
              q38 = sc_lv<DataWidth>();
    }
}


void prc_write_39()
{
    if (ce39.read() == sc_dt::Log_1) 
    {
            if(address39.read().is_01() && address39.read().to_uint()<AddressRange)
              q39 = ram[address39.read().to_uint()];
            else
              q39 = sc_lv<DataWidth>();
    }
}


void prc_write_40()
{
    if (ce40.read() == sc_dt::Log_1) 
    {
            if(address40.read().is_01() && address40.read().to_uint()<AddressRange)
              q40 = ram[address40.read().to_uint()];
            else
              q40 = sc_lv<DataWidth>();
    }
}


void prc_write_41()
{
    if (ce41.read() == sc_dt::Log_1) 
    {
            if(address41.read().is_01() && address41.read().to_uint()<AddressRange)
              q41 = ram[address41.read().to_uint()];
            else
              q41 = sc_lv<DataWidth>();
    }
}


void prc_write_42()
{
    if (ce42.read() == sc_dt::Log_1) 
    {
            if(address42.read().is_01() && address42.read().to_uint()<AddressRange)
              q42 = ram[address42.read().to_uint()];
            else
              q42 = sc_lv<DataWidth>();
    }
}


void prc_write_43()
{
    if (ce43.read() == sc_dt::Log_1) 
    {
            if(address43.read().is_01() && address43.read().to_uint()<AddressRange)
              q43 = ram[address43.read().to_uint()];
            else
              q43 = sc_lv<DataWidth>();
    }
}


void prc_write_44()
{
    if (ce44.read() == sc_dt::Log_1) 
    {
            if(address44.read().is_01() && address44.read().to_uint()<AddressRange)
              q44 = ram[address44.read().to_uint()];
            else
              q44 = sc_lv<DataWidth>();
    }
}


void prc_write_45()
{
    if (ce45.read() == sc_dt::Log_1) 
    {
            if(address45.read().is_01() && address45.read().to_uint()<AddressRange)
              q45 = ram[address45.read().to_uint()];
            else
              q45 = sc_lv<DataWidth>();
    }
}


void prc_write_46()
{
    if (ce46.read() == sc_dt::Log_1) 
    {
            if(address46.read().is_01() && address46.read().to_uint()<AddressRange)
              q46 = ram[address46.read().to_uint()];
            else
              q46 = sc_lv<DataWidth>();
    }
}


void prc_write_47()
{
    if (ce47.read() == sc_dt::Log_1) 
    {
            if(address47.read().is_01() && address47.read().to_uint()<AddressRange)
              q47 = ram[address47.read().to_uint()];
            else
              q47 = sc_lv<DataWidth>();
    }
}


void prc_write_48()
{
    if (ce48.read() == sc_dt::Log_1) 
    {
            if(address48.read().is_01() && address48.read().to_uint()<AddressRange)
              q48 = ram[address48.read().to_uint()];
            else
              q48 = sc_lv<DataWidth>();
    }
}


void prc_write_49()
{
    if (ce49.read() == sc_dt::Log_1) 
    {
            if(address49.read().is_01() && address49.read().to_uint()<AddressRange)
              q49 = ram[address49.read().to_uint()];
            else
              q49 = sc_lv<DataWidth>();
    }
}


void prc_write_50()
{
    if (ce50.read() == sc_dt::Log_1) 
    {
            if(address50.read().is_01() && address50.read().to_uint()<AddressRange)
              q50 = ram[address50.read().to_uint()];
            else
              q50 = sc_lv<DataWidth>();
    }
}


void prc_write_51()
{
    if (ce51.read() == sc_dt::Log_1) 
    {
            if(address51.read().is_01() && address51.read().to_uint()<AddressRange)
              q51 = ram[address51.read().to_uint()];
            else
              q51 = sc_lv<DataWidth>();
    }
}


void prc_write_52()
{
    if (ce52.read() == sc_dt::Log_1) 
    {
            if(address52.read().is_01() && address52.read().to_uint()<AddressRange)
              q52 = ram[address52.read().to_uint()];
            else
              q52 = sc_lv<DataWidth>();
    }
}


void prc_write_53()
{
    if (ce53.read() == sc_dt::Log_1) 
    {
            if(address53.read().is_01() && address53.read().to_uint()<AddressRange)
              q53 = ram[address53.read().to_uint()];
            else
              q53 = sc_lv<DataWidth>();
    }
}


void prc_write_54()
{
    if (ce54.read() == sc_dt::Log_1) 
    {
            if(address54.read().is_01() && address54.read().to_uint()<AddressRange)
              q54 = ram[address54.read().to_uint()];
            else
              q54 = sc_lv<DataWidth>();
    }
}


void prc_write_55()
{
    if (ce55.read() == sc_dt::Log_1) 
    {
            if(address55.read().is_01() && address55.read().to_uint()<AddressRange)
              q55 = ram[address55.read().to_uint()];
            else
              q55 = sc_lv<DataWidth>();
    }
}


void prc_write_56()
{
    if (ce56.read() == sc_dt::Log_1) 
    {
            if(address56.read().is_01() && address56.read().to_uint()<AddressRange)
              q56 = ram[address56.read().to_uint()];
            else
              q56 = sc_lv<DataWidth>();
    }
}


void prc_write_57()
{
    if (ce57.read() == sc_dt::Log_1) 
    {
            if(address57.read().is_01() && address57.read().to_uint()<AddressRange)
              q57 = ram[address57.read().to_uint()];
            else
              q57 = sc_lv<DataWidth>();
    }
}


void prc_write_58()
{
    if (ce58.read() == sc_dt::Log_1) 
    {
            if(address58.read().is_01() && address58.read().to_uint()<AddressRange)
              q58 = ram[address58.read().to_uint()];
            else
              q58 = sc_lv<DataWidth>();
    }
}


void prc_write_59()
{
    if (ce59.read() == sc_dt::Log_1) 
    {
            if(address59.read().is_01() && address59.read().to_uint()<AddressRange)
              q59 = ram[address59.read().to_uint()];
            else
              q59 = sc_lv<DataWidth>();
    }
}


void prc_write_60()
{
    if (ce60.read() == sc_dt::Log_1) 
    {
            if(address60.read().is_01() && address60.read().to_uint()<AddressRange)
              q60 = ram[address60.read().to_uint()];
            else
              q60 = sc_lv<DataWidth>();
    }
}


void prc_write_61()
{
    if (ce61.read() == sc_dt::Log_1) 
    {
            if(address61.read().is_01() && address61.read().to_uint()<AddressRange)
              q61 = ram[address61.read().to_uint()];
            else
              q61 = sc_lv<DataWidth>();
    }
}


void prc_write_62()
{
    if (ce62.read() == sc_dt::Log_1) 
    {
            if(address62.read().is_01() && address62.read().to_uint()<AddressRange)
              q62 = ram[address62.read().to_uint()];
            else
              q62 = sc_lv<DataWidth>();
    }
}


void prc_write_63()
{
    if (ce63.read() == sc_dt::Log_1) 
    {
            if(address63.read().is_01() && address63.read().to_uint()<AddressRange)
              q63 = ram[address63.read().to_uint()];
            else
              q63 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(encrypt_128_key_ebkb) {


static const unsigned DataWidth = 8;
static const unsigned AddressRange = 1024;
static const unsigned AddressWidth = 10;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in <sc_lv<AddressWidth> > address1;
sc_core::sc_in<sc_logic> ce1;
sc_core::sc_out <sc_lv<DataWidth> > q1;
sc_core::sc_in <sc_lv<AddressWidth> > address2;
sc_core::sc_in<sc_logic> ce2;
sc_core::sc_out <sc_lv<DataWidth> > q2;
sc_core::sc_in <sc_lv<AddressWidth> > address3;
sc_core::sc_in<sc_logic> ce3;
sc_core::sc_out <sc_lv<DataWidth> > q3;
sc_core::sc_in <sc_lv<AddressWidth> > address4;
sc_core::sc_in<sc_logic> ce4;
sc_core::sc_out <sc_lv<DataWidth> > q4;
sc_core::sc_in <sc_lv<AddressWidth> > address5;
sc_core::sc_in<sc_logic> ce5;
sc_core::sc_out <sc_lv<DataWidth> > q5;
sc_core::sc_in <sc_lv<AddressWidth> > address6;
sc_core::sc_in<sc_logic> ce6;
sc_core::sc_out <sc_lv<DataWidth> > q6;
sc_core::sc_in <sc_lv<AddressWidth> > address7;
sc_core::sc_in<sc_logic> ce7;
sc_core::sc_out <sc_lv<DataWidth> > q7;
sc_core::sc_in <sc_lv<AddressWidth> > address8;
sc_core::sc_in<sc_logic> ce8;
sc_core::sc_out <sc_lv<DataWidth> > q8;
sc_core::sc_in <sc_lv<AddressWidth> > address9;
sc_core::sc_in<sc_logic> ce9;
sc_core::sc_out <sc_lv<DataWidth> > q9;
sc_core::sc_in <sc_lv<AddressWidth> > address10;
sc_core::sc_in<sc_logic> ce10;
sc_core::sc_out <sc_lv<DataWidth> > q10;
sc_core::sc_in <sc_lv<AddressWidth> > address11;
sc_core::sc_in<sc_logic> ce11;
sc_core::sc_out <sc_lv<DataWidth> > q11;
sc_core::sc_in <sc_lv<AddressWidth> > address12;
sc_core::sc_in<sc_logic> ce12;
sc_core::sc_out <sc_lv<DataWidth> > q12;
sc_core::sc_in <sc_lv<AddressWidth> > address13;
sc_core::sc_in<sc_logic> ce13;
sc_core::sc_out <sc_lv<DataWidth> > q13;
sc_core::sc_in <sc_lv<AddressWidth> > address14;
sc_core::sc_in<sc_logic> ce14;
sc_core::sc_out <sc_lv<DataWidth> > q14;
sc_core::sc_in <sc_lv<AddressWidth> > address15;
sc_core::sc_in<sc_logic> ce15;
sc_core::sc_out <sc_lv<DataWidth> > q15;
sc_core::sc_in <sc_lv<AddressWidth> > address16;
sc_core::sc_in<sc_logic> ce16;
sc_core::sc_out <sc_lv<DataWidth> > q16;
sc_core::sc_in <sc_lv<AddressWidth> > address17;
sc_core::sc_in<sc_logic> ce17;
sc_core::sc_out <sc_lv<DataWidth> > q17;
sc_core::sc_in <sc_lv<AddressWidth> > address18;
sc_core::sc_in<sc_logic> ce18;
sc_core::sc_out <sc_lv<DataWidth> > q18;
sc_core::sc_in <sc_lv<AddressWidth> > address19;
sc_core::sc_in<sc_logic> ce19;
sc_core::sc_out <sc_lv<DataWidth> > q19;
sc_core::sc_in <sc_lv<AddressWidth> > address20;
sc_core::sc_in<sc_logic> ce20;
sc_core::sc_out <sc_lv<DataWidth> > q20;
sc_core::sc_in <sc_lv<AddressWidth> > address21;
sc_core::sc_in<sc_logic> ce21;
sc_core::sc_out <sc_lv<DataWidth> > q21;
sc_core::sc_in <sc_lv<AddressWidth> > address22;
sc_core::sc_in<sc_logic> ce22;
sc_core::sc_out <sc_lv<DataWidth> > q22;
sc_core::sc_in <sc_lv<AddressWidth> > address23;
sc_core::sc_in<sc_logic> ce23;
sc_core::sc_out <sc_lv<DataWidth> > q23;
sc_core::sc_in <sc_lv<AddressWidth> > address24;
sc_core::sc_in<sc_logic> ce24;
sc_core::sc_out <sc_lv<DataWidth> > q24;
sc_core::sc_in <sc_lv<AddressWidth> > address25;
sc_core::sc_in<sc_logic> ce25;
sc_core::sc_out <sc_lv<DataWidth> > q25;
sc_core::sc_in <sc_lv<AddressWidth> > address26;
sc_core::sc_in<sc_logic> ce26;
sc_core::sc_out <sc_lv<DataWidth> > q26;
sc_core::sc_in <sc_lv<AddressWidth> > address27;
sc_core::sc_in<sc_logic> ce27;
sc_core::sc_out <sc_lv<DataWidth> > q27;
sc_core::sc_in <sc_lv<AddressWidth> > address28;
sc_core::sc_in<sc_logic> ce28;
sc_core::sc_out <sc_lv<DataWidth> > q28;
sc_core::sc_in <sc_lv<AddressWidth> > address29;
sc_core::sc_in<sc_logic> ce29;
sc_core::sc_out <sc_lv<DataWidth> > q29;
sc_core::sc_in <sc_lv<AddressWidth> > address30;
sc_core::sc_in<sc_logic> ce30;
sc_core::sc_out <sc_lv<DataWidth> > q30;
sc_core::sc_in <sc_lv<AddressWidth> > address31;
sc_core::sc_in<sc_logic> ce31;
sc_core::sc_out <sc_lv<DataWidth> > q31;
sc_core::sc_in <sc_lv<AddressWidth> > address32;
sc_core::sc_in<sc_logic> ce32;
sc_core::sc_out <sc_lv<DataWidth> > q32;
sc_core::sc_in <sc_lv<AddressWidth> > address33;
sc_core::sc_in<sc_logic> ce33;
sc_core::sc_out <sc_lv<DataWidth> > q33;
sc_core::sc_in <sc_lv<AddressWidth> > address34;
sc_core::sc_in<sc_logic> ce34;
sc_core::sc_out <sc_lv<DataWidth> > q34;
sc_core::sc_in <sc_lv<AddressWidth> > address35;
sc_core::sc_in<sc_logic> ce35;
sc_core::sc_out <sc_lv<DataWidth> > q35;
sc_core::sc_in <sc_lv<AddressWidth> > address36;
sc_core::sc_in<sc_logic> ce36;
sc_core::sc_out <sc_lv<DataWidth> > q36;
sc_core::sc_in <sc_lv<AddressWidth> > address37;
sc_core::sc_in<sc_logic> ce37;
sc_core::sc_out <sc_lv<DataWidth> > q37;
sc_core::sc_in <sc_lv<AddressWidth> > address38;
sc_core::sc_in<sc_logic> ce38;
sc_core::sc_out <sc_lv<DataWidth> > q38;
sc_core::sc_in <sc_lv<AddressWidth> > address39;
sc_core::sc_in<sc_logic> ce39;
sc_core::sc_out <sc_lv<DataWidth> > q39;
sc_core::sc_in <sc_lv<AddressWidth> > address40;
sc_core::sc_in<sc_logic> ce40;
sc_core::sc_out <sc_lv<DataWidth> > q40;
sc_core::sc_in <sc_lv<AddressWidth> > address41;
sc_core::sc_in<sc_logic> ce41;
sc_core::sc_out <sc_lv<DataWidth> > q41;
sc_core::sc_in <sc_lv<AddressWidth> > address42;
sc_core::sc_in<sc_logic> ce42;
sc_core::sc_out <sc_lv<DataWidth> > q42;
sc_core::sc_in <sc_lv<AddressWidth> > address43;
sc_core::sc_in<sc_logic> ce43;
sc_core::sc_out <sc_lv<DataWidth> > q43;
sc_core::sc_in <sc_lv<AddressWidth> > address44;
sc_core::sc_in<sc_logic> ce44;
sc_core::sc_out <sc_lv<DataWidth> > q44;
sc_core::sc_in <sc_lv<AddressWidth> > address45;
sc_core::sc_in<sc_logic> ce45;
sc_core::sc_out <sc_lv<DataWidth> > q45;
sc_core::sc_in <sc_lv<AddressWidth> > address46;
sc_core::sc_in<sc_logic> ce46;
sc_core::sc_out <sc_lv<DataWidth> > q46;
sc_core::sc_in <sc_lv<AddressWidth> > address47;
sc_core::sc_in<sc_logic> ce47;
sc_core::sc_out <sc_lv<DataWidth> > q47;
sc_core::sc_in <sc_lv<AddressWidth> > address48;
sc_core::sc_in<sc_logic> ce48;
sc_core::sc_out <sc_lv<DataWidth> > q48;
sc_core::sc_in <sc_lv<AddressWidth> > address49;
sc_core::sc_in<sc_logic> ce49;
sc_core::sc_out <sc_lv<DataWidth> > q49;
sc_core::sc_in <sc_lv<AddressWidth> > address50;
sc_core::sc_in<sc_logic> ce50;
sc_core::sc_out <sc_lv<DataWidth> > q50;
sc_core::sc_in <sc_lv<AddressWidth> > address51;
sc_core::sc_in<sc_logic> ce51;
sc_core::sc_out <sc_lv<DataWidth> > q51;
sc_core::sc_in <sc_lv<AddressWidth> > address52;
sc_core::sc_in<sc_logic> ce52;
sc_core::sc_out <sc_lv<DataWidth> > q52;
sc_core::sc_in <sc_lv<AddressWidth> > address53;
sc_core::sc_in<sc_logic> ce53;
sc_core::sc_out <sc_lv<DataWidth> > q53;
sc_core::sc_in <sc_lv<AddressWidth> > address54;
sc_core::sc_in<sc_logic> ce54;
sc_core::sc_out <sc_lv<DataWidth> > q54;
sc_core::sc_in <sc_lv<AddressWidth> > address55;
sc_core::sc_in<sc_logic> ce55;
sc_core::sc_out <sc_lv<DataWidth> > q55;
sc_core::sc_in <sc_lv<AddressWidth> > address56;
sc_core::sc_in<sc_logic> ce56;
sc_core::sc_out <sc_lv<DataWidth> > q56;
sc_core::sc_in <sc_lv<AddressWidth> > address57;
sc_core::sc_in<sc_logic> ce57;
sc_core::sc_out <sc_lv<DataWidth> > q57;
sc_core::sc_in <sc_lv<AddressWidth> > address58;
sc_core::sc_in<sc_logic> ce58;
sc_core::sc_out <sc_lv<DataWidth> > q58;
sc_core::sc_in <sc_lv<AddressWidth> > address59;
sc_core::sc_in<sc_logic> ce59;
sc_core::sc_out <sc_lv<DataWidth> > q59;
sc_core::sc_in <sc_lv<AddressWidth> > address60;
sc_core::sc_in<sc_logic> ce60;
sc_core::sc_out <sc_lv<DataWidth> > q60;
sc_core::sc_in <sc_lv<AddressWidth> > address61;
sc_core::sc_in<sc_logic> ce61;
sc_core::sc_out <sc_lv<DataWidth> > q61;
sc_core::sc_in <sc_lv<AddressWidth> > address62;
sc_core::sc_in<sc_logic> ce62;
sc_core::sc_out <sc_lv<DataWidth> > q62;
sc_core::sc_in <sc_lv<AddressWidth> > address63;
sc_core::sc_in<sc_logic> ce63;
sc_core::sc_out <sc_lv<DataWidth> > q63;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


encrypt_128_key_ebkb_ram* meminst;


SC_CTOR(encrypt_128_key_ebkb) {
meminst = new encrypt_128_key_ebkb_ram("encrypt_128_key_ebkb_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->address1(address1);
meminst->ce1(ce1);
meminst->q1(q1);

meminst->address2(address2);
meminst->ce2(ce2);
meminst->q2(q2);

meminst->address3(address3);
meminst->ce3(ce3);
meminst->q3(q3);

meminst->address4(address4);
meminst->ce4(ce4);
meminst->q4(q4);

meminst->address5(address5);
meminst->ce5(ce5);
meminst->q5(q5);

meminst->address6(address6);
meminst->ce6(ce6);
meminst->q6(q6);

meminst->address7(address7);
meminst->ce7(ce7);
meminst->q7(q7);

meminst->address8(address8);
meminst->ce8(ce8);
meminst->q8(q8);

meminst->address9(address9);
meminst->ce9(ce9);
meminst->q9(q9);

meminst->address10(address10);
meminst->ce10(ce10);
meminst->q10(q10);

meminst->address11(address11);
meminst->ce11(ce11);
meminst->q11(q11);

meminst->address12(address12);
meminst->ce12(ce12);
meminst->q12(q12);

meminst->address13(address13);
meminst->ce13(ce13);
meminst->q13(q13);

meminst->address14(address14);
meminst->ce14(ce14);
meminst->q14(q14);

meminst->address15(address15);
meminst->ce15(ce15);
meminst->q15(q15);

meminst->address16(address16);
meminst->ce16(ce16);
meminst->q16(q16);

meminst->address17(address17);
meminst->ce17(ce17);
meminst->q17(q17);

meminst->address18(address18);
meminst->ce18(ce18);
meminst->q18(q18);

meminst->address19(address19);
meminst->ce19(ce19);
meminst->q19(q19);

meminst->address20(address20);
meminst->ce20(ce20);
meminst->q20(q20);

meminst->address21(address21);
meminst->ce21(ce21);
meminst->q21(q21);

meminst->address22(address22);
meminst->ce22(ce22);
meminst->q22(q22);

meminst->address23(address23);
meminst->ce23(ce23);
meminst->q23(q23);

meminst->address24(address24);
meminst->ce24(ce24);
meminst->q24(q24);

meminst->address25(address25);
meminst->ce25(ce25);
meminst->q25(q25);

meminst->address26(address26);
meminst->ce26(ce26);
meminst->q26(q26);

meminst->address27(address27);
meminst->ce27(ce27);
meminst->q27(q27);

meminst->address28(address28);
meminst->ce28(ce28);
meminst->q28(q28);

meminst->address29(address29);
meminst->ce29(ce29);
meminst->q29(q29);

meminst->address30(address30);
meminst->ce30(ce30);
meminst->q30(q30);

meminst->address31(address31);
meminst->ce31(ce31);
meminst->q31(q31);

meminst->address32(address32);
meminst->ce32(ce32);
meminst->q32(q32);

meminst->address33(address33);
meminst->ce33(ce33);
meminst->q33(q33);

meminst->address34(address34);
meminst->ce34(ce34);
meminst->q34(q34);

meminst->address35(address35);
meminst->ce35(ce35);
meminst->q35(q35);

meminst->address36(address36);
meminst->ce36(ce36);
meminst->q36(q36);

meminst->address37(address37);
meminst->ce37(ce37);
meminst->q37(q37);

meminst->address38(address38);
meminst->ce38(ce38);
meminst->q38(q38);

meminst->address39(address39);
meminst->ce39(ce39);
meminst->q39(q39);

meminst->address40(address40);
meminst->ce40(ce40);
meminst->q40(q40);

meminst->address41(address41);
meminst->ce41(ce41);
meminst->q41(q41);

meminst->address42(address42);
meminst->ce42(ce42);
meminst->q42(q42);

meminst->address43(address43);
meminst->ce43(ce43);
meminst->q43(q43);

meminst->address44(address44);
meminst->ce44(ce44);
meminst->q44(q44);

meminst->address45(address45);
meminst->ce45(ce45);
meminst->q45(q45);

meminst->address46(address46);
meminst->ce46(ce46);
meminst->q46(q46);

meminst->address47(address47);
meminst->ce47(ce47);
meminst->q47(q47);

meminst->address48(address48);
meminst->ce48(ce48);
meminst->q48(q48);

meminst->address49(address49);
meminst->ce49(ce49);
meminst->q49(q49);

meminst->address50(address50);
meminst->ce50(ce50);
meminst->q50(q50);

meminst->address51(address51);
meminst->ce51(ce51);
meminst->q51(q51);

meminst->address52(address52);
meminst->ce52(ce52);
meminst->q52(q52);

meminst->address53(address53);
meminst->ce53(ce53);
meminst->q53(q53);

meminst->address54(address54);
meminst->ce54(ce54);
meminst->q54(q54);

meminst->address55(address55);
meminst->ce55(ce55);
meminst->q55(q55);

meminst->address56(address56);
meminst->ce56(ce56);
meminst->q56(q56);

meminst->address57(address57);
meminst->ce57(ce57);
meminst->q57(q57);

meminst->address58(address58);
meminst->ce58(ce58);
meminst->q58(q58);

meminst->address59(address59);
meminst->ce59(ce59);
meminst->q59(q59);

meminst->address60(address60);
meminst->ce60(ce60);
meminst->q60(q60);

meminst->address61(address61);
meminst->ce61(ce61);
meminst->q61(q61);

meminst->address62(address62);
meminst->ce62(ce62);
meminst->q62(q62);

meminst->address63(address63);
meminst->ce63(ce63);
meminst->q63(q63);

meminst->reset(reset);
meminst->clk(clk);
}
~encrypt_128_key_ebkb() {
    delete meminst;
}


};//endmodule
#endif
