// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _AddRoundKey_HH_
#define _AddRoundKey_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct AddRoundKey : public sc_module {
    // Port declarations 15
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<6> > round;
    sc_out< sc_lv<4> > state_address0;
    sc_out< sc_logic > state_ce0;
    sc_out< sc_logic > state_we0;
    sc_out< sc_lv<32> > state_d0;
    sc_in< sc_lv<32> > state_q0;
    sc_out< sc_lv<8> > RoundKey_address0;
    sc_out< sc_logic > RoundKey_ce0;
    sc_in< sc_lv<32> > RoundKey_q0;


    // Module declarations
    AddRoundKey(sc_module_name name);
    SC_HAS_PROCESS(AddRoundKey);

    ~AddRoundKey();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<6> > i_cast4_cast_fu_82_p1;
    sc_signal< sc_lv<6> > i_cast4_cast_reg_183;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<3> > i_3_fu_92_p2;
    sc_signal< sc_lv<3> > i_3_reg_191;
    sc_signal< sc_lv<8> > tmp_cast_fu_110_p1;
    sc_signal< sc_lv<8> > tmp_cast_reg_196;
    sc_signal< sc_lv<1> > exitcond1_fu_86_p2;
    sc_signal< sc_lv<4> > state_addr_reg_201;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<3> > j_3_fu_142_p2;
    sc_signal< sc_lv<3> > j_3_reg_209;
    sc_signal< sc_lv<1> > exitcond_fu_136_p2;
    sc_signal< sc_lv<3> > i_reg_60;
    sc_signal< sc_lv<3> > j_reg_71;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<32> > tmp_25_cast_fu_131_p1;
    sc_signal< sc_lv<32> > sum3_cast_fu_166_p1;
    sc_signal< sc_lv<2> > tmp_fu_98_p1;
    sc_signal< sc_lv<4> > tmp_s_fu_102_p3;
    sc_signal< sc_lv<5> > tmp_16_fu_114_p3;
    sc_signal< sc_lv<6> > tmp_24_cast_fu_122_p1;
    sc_signal< sc_lv<6> > tmp_17_fu_126_p2;
    sc_signal< sc_lv<4> > tmp_38_fu_148_p1;
    sc_signal< sc_lv<8> > tmp1_fu_151_p4;
    sc_signal< sc_lv<8> > sum3_fu_161_p2;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_RoundKey_address0();
    void thread_RoundKey_ce0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exitcond1_fu_86_p2();
    void thread_exitcond_fu_136_p2();
    void thread_i_3_fu_92_p2();
    void thread_i_cast4_cast_fu_82_p1();
    void thread_j_3_fu_142_p2();
    void thread_state_address0();
    void thread_state_ce0();
    void thread_state_d0();
    void thread_state_we0();
    void thread_sum3_cast_fu_166_p1();
    void thread_sum3_fu_161_p2();
    void thread_tmp1_fu_151_p4();
    void thread_tmp_16_fu_114_p3();
    void thread_tmp_17_fu_126_p2();
    void thread_tmp_24_cast_fu_122_p1();
    void thread_tmp_25_cast_fu_131_p1();
    void thread_tmp_38_fu_148_p1();
    void thread_tmp_cast_fu_110_p1();
    void thread_tmp_fu_98_p1();
    void thread_tmp_s_fu_102_p3();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
